{
  Throwable t=extractException(runnable);
  assertException(wrapperExceptionClass2,t);
  assertException(wrapperExceptionClass1,t.getCause());
  assertException(exceptionClass,t.getCause().getCause());
}
