{
  try {
    return executeQuery(cache,query);
  }
 catch (  IOException e) {
    throw new CacheException("An exception has occurred during query execution",e);
  }
}
