{
  return throwable instanceof RemoteException && throwable.getCause() instanceof RetryPrepareException;
}
