{
  CompletableFuture<Map<Address,Response>> future=invokeRemotelyAsync(recipients,rpc,options);
  try {
    return future.get();
  }
 catch (  InterruptedException e) {
    Thread.currentThread().interrupt();
    throw new CacheException("Thread interrupted while invoking RPC",e);
  }
catch (  ExecutionException e) {
    Throwable cause=e.getCause();
    if (cause instanceof CacheException) {
      throw ((CacheException)cause);
    }
 else {
      throw new CacheException("Unexpected exception replicating command",cause);
    }
  }
}
