{
  try {
    return cf.get();
  }
 catch (  InterruptedException|ExecutionException e) {
    throw new Error(e);
  }
}
